apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: prometheus-huang
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
