apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus-huang
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: 'yoo2767@163.com'
      smtp_auth_username: 'yoo2767@163.com'
      smtp_auth_password: 'yoo2767'
      smtp_require_tls: false
      wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
      wechat_api_secret: 'faUWp7D9ArDgdUFjGAyXYvTHRLiuy19RVL4batCfTp4'
      wechat_api_corp_id: 'ww34d209d68573061d'
    receivers:
    - name: 'wechat'
      wechat_configs:
      - send_resolved: true
        to_party: '2'
        agent_id: '1000006'
        corp_id: 'ww34d209d68573061d'
        api_secret: 'faUWp7D9ArDgdUFjGAyXYvTHRLiuy19RVL4batCfTp4'
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: wechat
      repeat_interval: 3h
      group_by: ['alertname', 'k8scluster', 'node', 'container', 'exported_job', 'daemonset']
